    .section    .text
    .globl      main

main:
    addi        x1,         x0,         0       ;
    mulhsu      x3,         x2,         x1      ;
    mulhsu      x3,         x2,         x1      ;
    mulhsu      x3,         x2,         x1      ;
    mulhsu      x3,         x2,         x1      ;
    nop                                         ;
    nop                                         ;
    nop                                         ;
