    .section    .text
    .globl      main

main:
    addi        x1,         x0,         0       ;
    auipc       x8,         1                   ;
    auipc       x8,         1                   ;
    auipc       x8,         1                   ;
    auipc       x8,         1                   ;
    nop                                         ;
    nop                                         ;
    nop                                         ;
