    .section    .text
    .globl      _start
    .globl      main
_start:
main:
    addi        x1,         x0,         0       ;
    addi        x1,         x0,         1       ;
    addi        x1,         x0,         2       ;
    addi        x1,         x0,         4       ;
    addi        x1,         x0,         8       ;
    addi        x1,         x0,         16      ;
    addi        x1,         x0,         32      ;
    addi        x1,         x0,         64      ;
    addi        x1,         x0,         128     ;
    addi        x1,         x0,         256     ;
    addi        x2,         x1,         1       ;
